
name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'dbt_training'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  dbt_training:
    sale_dates:
      +column_types:
        SALE_DATE: date
        NAME: varchar
        DISCOUNT_PERCENT: number(18,2)

vars:
  default_date: '9999-01-01'

models:
  dbt_training:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
    

